[versions]
detekt = "1.23.6"
java = "17"
junit = "5.10.2"
kotest = "5.9.1"
kotlin = "2.0.0"
kover = "0.8.2"

[libraries]
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
