name: Dependency Submission

on:
  push: { branches: [ main ] }

jobs:
  dependency-submission:
    name: Dependency Submission
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v3
