name: Dependency Submission

on:
  push: { branches: [ main ] }

jobs:
  dependency-submission:
    name: Dependency Submission
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v3
